{"timestamp":"2025-09-04T12:03:00.842085","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-04T12:03:00.842675","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/f1_extract_migration.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-04T12:03:05.180825","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"URLError","exc_value":"<urlopen error [Errno -5] No address associated with hostname>","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/f1_extract_migration.py","lineno":47,"name":"extract_f1_sessions"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":215,"name":"urlopen"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":515,"name":"open"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":532,"name":"_open"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":492,"name":"_call_chain"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":1392,"name":"https_open"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":1347,"name":"do_open"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":1344,"name":"do_open"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1338,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1384,"name":"_send_request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1472,"name":"connect"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1003,"name":"connect"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":841,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
